### ISSUE TITLE
error in cmake

### ISSUE THREAD

**Issue by tiara567** [mech0ctopus/rrt-global-planner#2] opened 2022-08-22 08:07 UTC
Please help me deal with this error.

[100%] Building CXX object rrt-global-planner/CMakeFiles/rrt_global_planner_lib.dir/src/rrt.cpp.o
In file included from /home/user/catkin_ws/src/rrt-global-planner/include/rrt.hpp:20:0,
                 from /home/user/catkin_ws/src/rrt-global-planner/src/rrt.cpp:2:
/home/user/catkin_ws/src/rrt-global-planner/include/2d_space.hpp: In function ‘bool inFreeSpace(geometry_msgs::Point, const costmap_2d::Costmap2DROS*, double)’:
/home/user/catkin_ws/src/rrt-global-planner/include/2d_space.hpp:56:38: error: passing ‘const costmap_2d::Costmap2DROS’ as ‘this’ argument discards qualifiers [-fpermissive]
   costmap_ = costmap_ros->getCostmap();
                                      ^
In file included from /home/user/catkin_ws/src/rrt-global-planner/include/rrt.hpp:10:0,
                 from /home/user/catkin_ws/src/rrt-global-planner/src/rrt.cpp:2:
/opt/ros/melodic/include/costmap_2d/costmap_2d_ros.h:142:14: note:   in call to ‘costmap_2d::Costmap2D* costmap_2d::Costmap2DROS::getCostmap()’
   Costmap2D* getCostmap()
              ^~~~
rrt-global-planner/CMakeFiles/rrt_global_planner_lib.dir/build.make:62: recipe for target 'rrt-global-planner/CMakeFiles/rrt_global_planner_lib.dir/src/rrt.cpp.o' failed
make[2]: * [rrt-global-planner/CMakeFiles/rrt_global_planner_lib.dir/src/rrt.cpp.o] Error 1
CMakeFiles/Makefile2:10433: recipe for target 'rrt-global-planner/CMakeFiles/rrt_global_planner_lib.dir/all' failed
make[1]: * [rrt-global-planner/CMakeFiles/rrt_global_planner_lib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: * [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by mech0ctopus** [comment] 2022-08-23 22:13
Hi @tiara567, were you attempting to build this with `catkin_make`/`catkin build` or just using CMake directly? I'd recommend using the catkin tools.

The root cause seems related to the use of `const` with the costmap. Removing the `const` qualfier from `inFreeSpace` may be a quick fix to this issue.

Before:
`bool inFreeSpace(geometry_msgs::Point, const costmap_2d::Costmap2DROS*, double)`
After:
`bool inFreeSpace(geometry_msgs::Point, costmap_2d::Costmap2DROS*, double)`

Here is a SO post related to this: https://stackoverflow.com/questions/26963510/error-passing-const-as-this-argument-of-discards-qualifiers#26963552

**Comment by tiara567** [comment] 2022-08-24 08:11
Hi, @mech0ctopus 

Thank you so much. Your coding runs well.

**Comment by mech0ctopus** [comment] 2022-08-25 21:56
Awesome, I'll close this issue. Please feel free to open another if you run into anymore problems.

**Closed as completed by mech0ctopus** 2022-08-25 21:56 UTC
